# Generated by Django 2.0.3 on 2020-08-19 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('dob', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('email', models.CharField(default='', max_length=100)),
                ('department', models.CharField(choices=[('accountant', 'Accountant'), ('hr', 'HR'), ('marketing', 'Marketing'), ('network', 'Network'), ('operation_manager', 'Operation Manager'), ('it_production', 'IT Production')], default='it_production', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('salary', models.CharField(default='', max_length=100)),
                ('address', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
